# Site
repository: erclu/my-cv
favicon: assets/images/logo.png

# Personal info
name: Luca Ercole
title: Studente LT in Informatica
address: Padova (PD)
email: luca.ercole.90@gmail.com
phone: +39 333 3476 981
# website: https://erclu.github.io/my-cv # TODO decide if i should keep it
# TODO add QR code in print version

# About Section
about_title: Chi sono

# Projects Section
projects_title: Progetti

# Experience Section
experience_title: Esperienza lavorativa

# Education Section
education_title: Istruzione e formazione

# More Section
more_title: Hobby e interessi # (comment to hide section)

# Data consent Section
# show_data_consent: true

# Footer
# footer_show_references: true
# TODO tradurre footer.html in ita

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
