# Site
repository: erclu/my-cv
favicon: assets/images/logo.png

# TODO put this section into external file (why?)
# Personal info
name: Luca Ercole
title: Studente LT in Informatica
address: Padova (PD)
email: luca.ercole.90@gmail.com
phone: +39 333 3476 981
website: https://erclu.github.io/my-cv # FIXME

# Social links
# twitter_username: jekyllrb
github_username: erclu
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: # TODO linkedin
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
about_title: Chi sono

# Projects Section
projects_title: Progetti

# Experience Section
experience_title: Esperienza lavorativa

# Education Section
education_title: Istruzione e formazione

# More Section
more_title: Hobby e interessi # (comment to hide section)

# Data consent Section
# show_data_consent: true

# Footer
footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
