# Jekyll ignore
exclude:
  - .bundle
  - .vscode
  - vendor
  - "*.code-workspace"
  - .prettierrc.json
  - publish.ps1

# Site
repository: erclu/my-cv
favicon: assets/images/logo-transparent.png
title: Luca Ercole - CV
author: Luca Ercole

# Google Analytics (#XXX disabled until I can be compliant with GDPR)
ga_enabled: false
ga_property: UA-137567490-1

# About Section
about_title: Chi sono

# Projects Section
projects_title: Progetti

# Experience Section
experience_title: Esperienza lavorativa

# Education Section
education_title: Istruzione e formazione

# More Section
more_title: Hobby e interessi # (comment to hide section)

# Footer
show_data_consent: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
