# Site
repository: erclu/my-cv
favicon: assets/images/logo.png
google_analytics: true #XXX not sure about this

# Personal info
name: Luca Ercole
title: Studente LT in Informatica
website: erclu.github.io/my-cv
email: luca.ercole.90@gmail.com
address: Padova (PD)
# phone: ...

# About Section
about_title: Chi sono

# Projects Section
projects_title: Progetti

# Experience Section
experience_title: Esperienza lavorativa

# Education Section
education_title: Istruzione e formazione

# More Section
more_title: Hobby e interessi # (comment to hide section)

# Footer
show_data_consent: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
